"""empty message

Revision ID: 971aa2d02bfd
Revises: cfc4c597a9ea
Create Date: 2019-06-01 22:10:06.618198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '971aa2d02bfd'
down_revision = 'cfc4c597a9ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('registered_on', sa.DateTime(), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.add_column('sf_food_trucks', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sf_food_trucks', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sf_food_trucks', type_='foreignkey')
    op.drop_column('sf_food_trucks', 'user_id')
    op.drop_table('users')
    # ### end Alembic commands ###
