"""empty message

Revision ID: cf1e08118a02
Revises: fa67eb751383
Create Date: 2019-05-18 17:58:22.738117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf1e08118a02'
down_revision = 'fa67eb751383'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sf_food_trucks',
    sa.Column('uuid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('days_hours', sa.String(), nullable=True),
    sa.Column('food_items', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_sf_food_trucks_latitude'), 'sf_food_trucks', ['latitude'], unique=False)
    op.create_index(op.f('ix_sf_food_trucks_longitude'), 'sf_food_trucks', ['longitude'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sf_food_trucks_longitude'), table_name='sf_food_trucks')
    op.drop_index(op.f('ix_sf_food_trucks_latitude'), table_name='sf_food_trucks')
    op.drop_table('sf_food_trucks')
    # ### end Alembic commands ###
