"""empty message

Revision ID: fa67eb751383
Revises: 
Create Date: 2019-05-14 22:17:21.852847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa67eb751383'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sf_food_trucks',
    sa.Column('uuid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('days_hours', sa.String(), nullable=True),
    sa.Column('food_items', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sf_food_trucks')
    # ### end Alembic commands ###
